security:
  oauth2:
    client:
      clientId: 304615777021427
      clientSecret: 6f5f19d2b2e4e5d36e19bd6d4c2b8edb
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me